### ISSUE TITLE
restrict access based on IP address/domain

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_admin_webapp#8]
Only curators should access the admin dashboard. To avoid a more sophisticated authentication system, we can use the same strategy used by the curation status form based on white lists on IP addresses/domains. I can allow access to all caltech machines (including VPN) and deny all other IPs. Is this ok with you @draciti and @vanaukenk?

**Comment by valearna** [comment]
The IP filter is already in place. Let me know if you can access the page through the VPN.

**Comment by azurebrd** [comment]
Oh, didn't realize the IP list was for this.  I don't think that I specifically have an IP for the Caltech VPN, instead tazendra whitelists some IPs, and for those IPs that don't match the list, there's a login / password.

**Comment by draciti** [comment]
this is ok and it works fine at my end. Closing
